import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-800`}>
        <header className="bg-gray-900 text-white shadow">
          <nav className="max-w-6xl mx-auto flex items-center justify-between px-6 py-4">
            <div className="text-xl font-bold">News Site</div>
            <ul className="flex space-x-6 text-base font-medium">
              <li>
                <Link href="/" className="hover:text-gray-300 transition">Home</Link>
              </li>
              <li>
                <Link href="/about-us" className="hover:text-gray-300 transition">About</Link>
              </li>
              <li>
                <Link href="/categories" className="hover:text-gray-300 transition">Categories</Link>
              </li>

            </ul>
          </nav>
        </header>

        <main className="max-h-[calc(100vh-130px)]">
          {children}
        </main>

        <footer className="bg-gray-900 text-white text-center py-6">
          &copy; {new Date().getFullYear()} News Site. All rights reserved Nada Mohamed Ahmed.
        </footer>
      </body>

    </html>
  );
}
